# Generated by Django 3.1.14 on 2023-04-14 08:59

from django.db import migrations


def get_new_buildings(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    flats.objects.filter(construction_year__gt=2014).update(new_building=True)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(get_new_buildings)
    ]
