# Generated by Django 3.1.14 on 2023-04-14 08:59

from django.db import migrations


def get_new_buildings(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_buildings = Flat.objects.filter(construction_year__gt=2014)
    for flat in new_buildings:
        flat.new_building = True
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(get_new_buildings)
    ]
