# Generated by Django 4.2 on 2023-04-15 12:28
import phonenumbers
from django.db import migrations


def validate_phone_number(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    flats = Flats.objects.all()
    for flat in flats.iterator():
        owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(owner_pure_phone):
            flat.owner_pure_phone = phonenumbers.format_number(owner_pure_phone, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0006_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(validate_phone_number)
    ]
