# Generated by Django 4.2 on 2023-04-16 16:17

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    Owners = apps.get_model('property', 'Owner')
    for flat in Flats.objects.all():
        Owners.objects.update_or_create(name=flat.owner, phonenumber=flat.owners_phonenumber,
                                        pure_phonenumber=flat.owner_pure_phone)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_alter_flat_owner_pure_phone_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
