# Generated by Django 4.2 on 2023-04-16 16:17

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owners = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner, created = Owners.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owner_pure_phone
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_alter_flat_owner_pure_phone_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
