# Generated by Django 4.2 on 2023-04-16 17:35

from django.db import migrations


def add_flats_to_owner(apps, schema_editor):
    flats_model = apps.get_model('property', 'Flat')
    owners_model = apps.get_model('property', 'Owner')
    flats = flats_model.objects.all()
    for flat in flats.iterator():
        owners = owners_model.objects.filter(name=flat.owner)
        for owner in owners:
            owner.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_auto_20230416_1917'),
    ]

    operations = [
        migrations.RunPython(add_flats_to_owner)
    ]
