# Generated by Django 4.2 on 2023-05-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230416_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Flat',
            name='owner'
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber'
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owner_pure_phone'
        )
    ]
