# Generated by Django 4.2 on 2023-04-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230416_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Flat',
            name='owner'
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber'
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owner_pure_phone'
        )
    ]
